/**
 * Copy key constants for VillageCircle360 UX layer.
 * Use these keys with getCopy() so copy is centralised and audit-friendly.
 *
 * Naming: area_context_element (e.g. common_button_retry, member_dashboard_savingsTotal).
 *
 * @see lib/copy/messages.ts
 * @see docs/DESIGN_SYSTEM.md
 */

export const COPY_KEYS = {
  // Common – buttons, states, errors
  common_button_back: 'common_button_back',
  common_button_cancel: 'common_button_cancel',
  common_button_confirm: 'common_button_confirm',
  common_button_retry: 'common_button_retry',
  common_button_submit: 'common_button_submit',
  common_error_generic: 'common_error_generic',
  common_loading: 'common_loading',
  common_empty_title: 'common_empty_title',
  common_permissionDenied: 'common_permissionDenied',
  /** Example templated: use getCopyTemplate(KEY, { amount, groupName }) */
  common_exampleRecordSummary: 'common_exampleRecordSummary',

  // VC Save – dashboard card and perimeter (MVP: records only, no in-app money movement)
  save_dashboard_card_title: 'save_dashboard_card_title',
  save_dashboard_card_description: 'save_dashboard_card_description',
  save_dashboard_card_description_short: 'save_dashboard_card_description_short',
  save_mvp_perimeter: 'save_mvp_perimeter',

  // VC Save – statement bucket labels (Savings vs Social Fund kept distinct)
  save_bucket_savings: 'save_bucket_savings',
  save_bucket_socialFund: 'save_bucket_socialFund',
  save_bucket_loanPrincipal: 'save_bucket_loanPrincipal',
  save_bucket_interest: 'save_bucket_interest',
  save_bucket_penalties: 'save_bucket_penalties',
  save_contribution_recordType: 'save_contribution_recordType',

  // VC Save – transaction mode (mixed-mode entry)
  save_transactionMode_label: 'save_transactionMode_label',
  save_transactionMode_cash: 'save_transactionMode_cash',
  save_transactionMode_cashShort: 'save_transactionMode_cashShort',
  save_transactionMode_bank: 'save_transactionMode_bank',
  save_transactionMode_bankShort: 'save_transactionMode_bankShort',
  save_transactionMode_hint: 'save_transactionMode_hint',

  // VC Save – external reference (tracking only; no execution)
  save_externalRef_placeholder: 'save_externalRef_placeholder',
  save_externalRef_hintBank: 'save_externalRef_hintBank',
  save_externalRef_hintCash: 'save_externalRef_hintCash',

  // VC Save – evidence
  save_evidence_label: 'save_evidence_label',
  save_evidence_uploadHelper: 'save_evidence_uploadHelper',
  save_evidence_lockedExplanation: 'save_evidence_lockedExplanation',
  save_evidence_optionalDetail: 'save_evidence_optionalDetail',

  // VC Save – batch review and totals (savings vs social fund separate)
  save_batch_summaryTitle: 'save_batch_summaryTitle',
  save_batch_savingsTotal: 'save_batch_savingsTotal',
  save_batch_socialFundTotal: 'save_batch_socialFundTotal',
  save_batch_totalCollected: 'save_batch_totalCollected',
  save_batch_cashCount: 'save_batch_cashCount',
  save_batch_bankCount: 'save_batch_bankCount',
  save_batch_willBeRecorded: 'save_batch_willBeRecorded',
  save_batch_submitting: 'save_batch_submitting',
  save_contribution_success: 'save_contribution_success',
  save_reconciliation_heading: 'save_reconciliation_heading',
  save_reconciliation_disclaimer: 'save_reconciliation_disclaimer',

  // Member (VC Save / VC Hub – dashboard, statements, contributions)
  member_dashboard_title: 'member_dashboard_title',
  member_dashboard_subtitle: 'member_dashboard_subtitle',
  member_dashboard_savingsTotal: 'member_dashboard_savingsTotal',
  member_dashboard_socialFundTotal: 'member_dashboard_socialFundTotal',
  member_dashboard_activeLoanBalance: 'member_dashboard_activeLoanBalance',
  member_dashboard_errorLoad: 'member_dashboard_errorLoad',
  member_dashboard_recentActivity: 'member_dashboard_recentActivity',
  member_dashboard_noRecentActivity: 'member_dashboard_noRecentActivity',
  member_dashboard_noRecentActivityDescription: 'member_dashboard_noRecentActivityDescription',
  member_dashboard_viewStatements: 'member_dashboard_viewStatements',
  member_dashboard_upcoming: 'member_dashboard_upcoming',
  member_dashboard_noUpcomingMeetings: 'member_dashboard_noUpcomingMeetings',
  member_dashboard_noUpcomingMeetingsDescription: 'member_dashboard_noUpcomingMeetingsDescription',
  member_statements_title: 'member_statements_title',
  member_statements_errorLoad: 'member_statements_errorLoad',
  member_statements_entriesByBucket: 'member_statements_entriesByBucket',
  member_statements_noEntries: 'member_statements_noEntries',
  member_statements_emptyDescription: 'member_statements_emptyDescription',
  member_statements_dateFrom: 'member_statements_dateFrom',
  member_statements_dateTo: 'member_statements_dateTo',
  member_statements_exportUnavailable: 'member_statements_exportUnavailable',
  member_statements_exportUnavailableHint: 'member_statements_exportUnavailableHint',
  member_contribution_recorded: 'member_contribution_recorded',
  member_mvp_disclaimer: 'member_mvp_disclaimer',
  member_backToDashboard: 'member_backToDashboard',

  // Treasurer / Operations – meeting entry (VC Save)
  ops_meeting_entry_title: 'ops_meeting_entry_title',
  ops_meeting_entry_backToMeetings: 'ops_meeting_entry_backToMeetings',
  ops_meeting_entry_helpText: 'ops_meeting_entry_helpText',
  ops_meeting_entry_savingsLabel: 'ops_meeting_entry_savingsLabel',
  ops_meeting_entry_socialFundLabel: 'ops_meeting_entry_socialFundLabel',
  ops_meeting_entry_totalLabel: 'ops_meeting_entry_totalLabel',
  ops_meeting_entry_markAbsent: 'ops_meeting_entry_markAbsent',
  ops_meeting_entry_includeMember: 'ops_meeting_entry_includeMember',
  ops_meeting_entry_reviewSubmit: 'ops_meeting_entry_reviewSubmit',
  ops_meeting_entry_submitBatch: 'ops_meeting_entry_submitBatch',
  ops_meeting_entry_submitting: 'ops_meeting_entry_submitting',
  ops_meeting_entry_backToEntry: 'ops_meeting_entry_backToEntry',
  ops_meeting_entry_noMembersTitle: 'ops_meeting_entry_noMembersTitle',
  ops_meeting_entry_noMembersDescription: 'ops_meeting_entry_noMembersDescription',
  ops_meeting_entry_errorLoadMembers: 'ops_meeting_entry_errorLoadMembers',
  ops_meeting_detail_title: 'ops_meeting_detail_title',
  ops_meeting_detail_addMoreEntries: 'ops_meeting_detail_addMoreEntries',
  ops_meeting_detail_errorLoad: 'ops_meeting_detail_errorLoad',
  ops_meeting_detail_totalsHeading: 'ops_meeting_detail_totalsHeading',
  ops_contribution_reverse: 'ops_contribution_reverse',
  ops_contribution_reversalReasonRequired: 'ops_contribution_reversalReasonRequired',
  ops_contribution_reversalDialogTitle: 'ops_contribution_reversalDialogTitle',
  ops_loan_approve: 'ops_loan_approve',
  ops_loan_repay_record: 'ops_loan_repay_record',
  ops_loan_repay_duplicateMessage: 'ops_loan_repay_duplicateMessage',
  ops_mvp_recorded_not_executed: 'ops_mvp_recorded_not_executed',

  // VC Hub – dashboard, group, governance, meetings, approvals, share-out
  hub_dashboard_card_title: 'hub_dashboard_card_title',
  hub_dashboard_card_description: 'hub_dashboard_card_description',
  hub_onboarding_description: 'hub_onboarding_description',
  hub_group_creation_title: 'hub_group_creation_title',
  hub_group_creation_description: 'hub_group_creation_description',
  hub_roles_heading: 'hub_roles_heading',
  hub_roles_helperText: 'hub_roles_helperText',
  hub_meeting_setup_heading: 'hub_meeting_setup_heading',
  hub_meeting_selectOrCreate: 'hub_meeting_selectOrCreate',
  hub_meeting_newMeeting: 'hub_meeting_newMeeting',
  hub_meeting_dateLabel: 'hub_meeting_dateLabel',
  hub_meeting_nameLabel: 'hub_meeting_nameLabel',
  hub_meeting_namePlaceholder: 'hub_meeting_namePlaceholder',
  hub_meeting_createAndEnter: 'hub_meeting_createAndEnter',
  hub_meeting_creating: 'hub_meeting_creating',
  hub_meeting_noMeetingsTitle: 'hub_meeting_noMeetingsTitle',
  hub_meeting_noMeetingsDescription: 'hub_meeting_noMeetingsDescription',
  hub_meeting_attendance_heading: 'hub_meeting_attendance_heading',
  hub_meeting_reopen_warningTitle: 'hub_meeting_reopen_warningTitle',
  hub_meeting_reopen_warningBody: 'hub_meeting_reopen_warningBody',
  hub_approval_queue_heading: 'hub_approval_queue_heading',
  hub_approval_approveLoan: 'hub_approval_approveLoan',
  hub_approval_rejectLoan: 'hub_approval_rejectLoan',
  hub_approval_confirmApprove: 'hub_approval_confirmApprove',
  hub_approval_confirmReject: 'hub_approval_confirmReject',
  hub_approval_applicationApproved: 'hub_approval_applicationApproved',
  hub_approval_applicationRejected: 'hub_approval_applicationRejected',
  hub_approval_applicantNotified: 'hub_approval_applicantNotified',
  hub_approval_viewOnlyHeading: 'hub_approval_viewOnlyHeading',
  hub_approval_viewOnlyDescription: 'hub_approval_viewOnlyDescription',
  hub_approval_makingDecisionDescription: 'hub_approval_makingDecisionDescription',
  hub_rules_heading: 'hub_rules_heading',
  hub_rules_helperText: 'hub_rules_helperText',
  hub_rule_change_warningTitle: 'hub_rule_change_warningTitle',
  hub_rule_change_warningBody: 'hub_rule_change_warningBody',
  hub_rule_versioned_note: 'hub_rule_versioned_note',
  hub_shareout_draft_label: 'hub_shareout_draft_label',
  hub_shareout_draft_description: 'hub_shareout_draft_description',
  hub_shareout_final_label: 'hub_shareout_final_label',
  hub_shareout_final_description: 'hub_shareout_final_description',
  hub_audit_transparency_heading: 'hub_audit_transparency_heading',
  hub_audit_transparency_description: 'hub_audit_transparency_description',
  hub_permission_denied_title: 'hub_permission_denied_title',
  hub_permission_denied_message: 'hub_permission_denied_message',
  hub_permission_denied_contactAdmin: 'hub_permission_denied_contactAdmin',
  hub_meetings_page_title: 'hub_meetings_page_title',
  hub_meetings_page_emptyTitle: 'hub_meetings_page_emptyTitle',
  hub_meetings_page_emptyDescription: 'hub_meetings_page_emptyDescription',
  hub_audit_log_title: 'hub_audit_log_title',
  hub_audit_log_placeholderDescription: 'hub_audit_log_placeholderDescription',
  hub_backToContributions: 'hub_backToContributions',
  hub_backToLoans: 'hub_backToLoans',
  hub_backToDashboard: 'hub_backToDashboard',
  hub_errorLoadMeetings: 'hub_errorLoadMeetings',
  hub_errorLoadApplication: 'hub_errorLoadApplication',

  // VC Grow – loan application, approvals, repayment, schedule, exceptions (MVP: records only; no platform lending)
  grow_dashboard_card_title: 'grow_dashboard_card_title',
  grow_dashboard_card_description: 'grow_dashboard_card_description',
  grow_mvp_perimeter: 'grow_mvp_perimeter',
  grow_mvp_loan_disclaimer: 'grow_mvp_loan_disclaimer',
  grow_loan_request_title: 'grow_loan_request_title',
  grow_loan_request_backToLoans: 'grow_loan_request_backToLoans',
  grow_loan_request_groupPolicyHeading: 'grow_loan_request_groupPolicyHeading',
  grow_interest_enabled: 'grow_interest_enabled',
  grow_interest_disabled: 'grow_interest_disabled',
  grow_interest_mayApply: 'grow_interest_mayApply',
  grow_interest_doesNotApply: 'grow_interest_doesNotApply',
  grow_loan_request_amountLabel: 'grow_loan_request_amountLabel',
  grow_loan_request_termLabel: 'grow_loan_request_termLabel',
  grow_loan_request_termPlaceholder: 'grow_loan_request_termPlaceholder',
  grow_loan_request_termErrorRequired: 'grow_loan_request_termErrorRequired',
  grow_loan_request_termErrorInvalid: 'grow_loan_request_termErrorInvalid',
  grow_loan_request_purposeLabel: 'grow_loan_request_purposeLabel',
  grow_loan_request_purposePlaceholder: 'grow_loan_request_purposePlaceholder',
  grow_loan_request_continue: 'grow_loan_request_continue',
  grow_loan_request_confirmHeading: 'grow_loan_request_confirmHeading',
  grow_loan_request_submit: 'grow_loan_request_submit',
  grow_loan_request_submitting: 'grow_loan_request_submitting',
  grow_ruleSnapshot_heading: 'grow_ruleSnapshot_heading',
  grow_ruleSnapshot_interestLabel: 'grow_ruleSnapshot_interestLabel',
  grow_ruleSnapshot_termLabel: 'grow_ruleSnapshot_termLabel',
  grow_repay_title: 'grow_repay_title',
  grow_repay_backToLoan: 'grow_repay_backToLoan',
  grow_repay_loanSummaryHeading: 'grow_repay_loanSummaryHeading',
  grow_repay_outstandingLabel: 'grow_repay_outstandingLabel',
  grow_repay_allocationOrderExplainer: 'grow_repay_allocationOrderExplainer',
  grow_repay_duplicateMessage: 'grow_repay_duplicateMessage',
  grow_repay_success: 'grow_repay_success',
  grow_repay_allocatedPrincipal: 'grow_repay_allocatedPrincipal',
  grow_repay_allocatedInterest: 'grow_repay_allocatedInterest',
  grow_repay_allocatedPenalty: 'grow_repay_allocatedPenalty',
  grow_repay_evidenceLinkedNote: 'grow_repay_evidenceLinkedNote',
  grow_repay_amountLabel: 'grow_repay_amountLabel',
  grow_repay_transactionModeRequired: 'grow_repay_transactionModeRequired',
  grow_repay_recording: 'grow_repay_recording',
  grow_repay_recordButton: 'grow_repay_recordButton',
  grow_repay_recordButtonShort: 'grow_repay_recordButtonShort',
  grow_repay_loanNotActive: 'grow_repay_loanNotActive',
  grow_repay_noOutstanding: 'grow_repay_noOutstanding',
  grow_repay_errorLoadLoan: 'grow_repay_errorLoadLoan',
  grow_loan_detail_title: 'grow_loan_detail_title',
  grow_loan_detail_backToActive: 'grow_loan_detail_backToActive',
  grow_loan_detail_loanStateHeading: 'grow_loan_detail_loanStateHeading',
  grow_loan_detail_principalLabel: 'grow_loan_detail_principalLabel',
  grow_loan_detail_totalRepaidLabel: 'grow_loan_detail_totalRepaidLabel',
  grow_loan_detail_outstandingLabel: 'grow_loan_detail_outstandingLabel',
  grow_loan_detail_ruleSnapshotHeading: 'grow_loan_detail_ruleSnapshotHeading',
  grow_loan_detail_interestEnabled: 'grow_loan_detail_interestEnabled',
  grow_loan_detail_interestDisabled: 'grow_loan_detail_interestDisabled',
  grow_loan_detail_scheduleHeading: 'grow_loan_detail_scheduleHeading',
  grow_loan_detail_scheduleEmptyDescription: 'grow_loan_detail_scheduleEmptyDescription',
  grow_loan_detail_scheduleConfidenceNote: 'grow_loan_detail_scheduleConfidenceNote',
  grow_loan_detail_exceptionHistoryHeading: 'grow_loan_detail_exceptionHistoryHeading',
  grow_loan_detail_repaymentHistoryHeading: 'grow_loan_detail_repaymentHistoryHeading',
  grow_loan_detail_noRepaymentsYet: 'grow_loan_detail_noRepaymentsYet',
  grow_loan_detail_noRepaymentsDescription: 'grow_loan_detail_noRepaymentsDescription',
  grow_loan_detail_actionsHeading: 'grow_loan_detail_actionsHeading',
  grow_loan_detail_recordWaiver: 'grow_loan_detail_recordWaiver',
  grow_loan_detail_reschedule: 'grow_loan_detail_reschedule',
  grow_loan_detail_writeOff: 'grow_loan_detail_writeOff',
  grow_loan_detail_recordRepaymentLink: 'grow_loan_detail_recordRepaymentLink',
  grow_loan_detail_waiverRecorded: 'grow_loan_detail_waiverRecorded',
  grow_loan_detail_rescheduleRecorded: 'grow_loan_detail_rescheduleRecorded',
  grow_loan_detail_writeOffRecorded: 'grow_loan_detail_writeOffRecorded',
  grow_loan_detail_waiverDialogTitle: 'grow_loan_detail_waiverDialogTitle',
  grow_loan_detail_waiverDialogBody: 'grow_loan_detail_waiverDialogBody',
  grow_loan_detail_rescheduleDialogTitle: 'grow_loan_detail_rescheduleDialogTitle',
  grow_loan_detail_rescheduleDialogBody: 'grow_loan_detail_rescheduleDialogBody',
  grow_loan_detail_writeOffDialogTitle: 'grow_loan_detail_writeOffDialogTitle',
  grow_loan_detail_writeOffDialogBody: 'grow_loan_detail_writeOffDialogBody',
  grow_loan_detail_errorLoadLoan: 'grow_loan_detail_errorLoadLoan',
  grow_overdue_reminderNote: 'grow_overdue_reminderNote',

  // Legal and compliance (placeholders for counsel-approved text; UK wording style)
  legal_termsSummary_short: 'legal_termsSummary_short',
  legal_termsSummary_full: 'legal_termsSummary_full',
  legal_privacySummary_short: 'legal_privacySummary_short',
  legal_privacySummary_full: 'legal_privacySummary_full',
  legal_nonBankDisclaimer_short: 'legal_nonBankDisclaimer_short',
  legal_nonBankDisclaimer_full: 'legal_nonBankDisclaimer_full',
  legal_recordkeepingNotice_save_short: 'legal_recordkeepingNotice_save_short',
  legal_recordkeepingNotice_save_full: 'legal_recordkeepingNotice_save_full',
  legal_recordkeepingNotice_hub_short: 'legal_recordkeepingNotice_hub_short',
  legal_recordkeepingNotice_hub_full: 'legal_recordkeepingNotice_hub_full',
  legal_recordkeepingNotice_grow_short: 'legal_recordkeepingNotice_grow_short',
  legal_recordkeepingNotice_grow_full: 'legal_recordkeepingNotice_grow_full',
  legal_evidenceUploadNotice_short: 'legal_evidenceUploadNotice_short',
  legal_evidenceUploadNotice_full: 'legal_evidenceUploadNotice_full',
  legal_supportAccessNotice_short: 'legal_supportAccessNotice_short',
  legal_supportAccessNotice_full: 'legal_supportAccessNotice_full',
  legal_onboarding_disclaimer_short: 'legal_onboarding_disclaimer_short',
  legal_onboarding_disclaimer_full: 'legal_onboarding_disclaimer_full',
  legal_permissionDenied_inline: 'legal_permissionDenied_inline',
  legal_permissionDenied_contactAdmin: 'legal_permissionDenied_contactAdmin',
  legal_supportReason_prompt: 'legal_supportReason_prompt',
  legal_supportReason_warning: 'legal_supportReason_warning',
  legal_supportReason_requiredFields: 'legal_supportReason_requiredFields',
  legal_supportReason_caseIdLabel: 'legal_supportReason_caseIdLabel',
  legal_supportReason_tenantIdLabel: 'legal_supportReason_tenantIdLabel',
  legal_supportReason_actorIdLabel: 'legal_supportReason_actorIdLabel',
  legal_supportEvidence_auditedBanner: 'legal_supportEvidence_auditedBanner',
  legal_supportEvidence_accessDenied: 'legal_supportEvidence_accessDenied',
  legal_supportEvidence_gateTitle: 'legal_supportEvidence_gateTitle',

  // Notifications
  notifications_preferences_title: 'notifications_preferences_title',
  notifications_sms_nonCritical: 'notifications_sms_nonCritical',
  // notifications.common.*
  notifications_common_emptyTitle: 'notifications_common_emptyTitle',
  notifications_common_emptyDescription: 'notifications_common_emptyDescription',
  notifications_common_errorLoad: 'notifications_common_errorLoad',
  notifications_common_ctaView: 'notifications_common_ctaView',
  notifications_common_statusSending: 'notifications_common_statusSending',
  notifications_common_statusFailed: 'notifications_common_statusFailed',
  notifications_common_failureGeneric: 'notifications_common_failureGeneric',
  // notifications.meeting.*
  notifications_meeting_reminder_title_inApp: 'notifications_meeting_reminder_title_inApp',
  notifications_meeting_reminder_title_sms: 'notifications_meeting_reminder_title_sms',
  notifications_meeting_reminder_body_inApp: 'notifications_meeting_reminder_body_inApp',
  notifications_meeting_reminder_body_sms: 'notifications_meeting_reminder_body_sms',
  notifications_meeting_reminder_cta: 'notifications_meeting_reminder_cta',
  // notifications.contribution.*
  notifications_contribution_dueReminder_title_inApp: 'notifications_contribution_dueReminder_title_inApp',
  notifications_contribution_dueReminder_title_sms: 'notifications_contribution_dueReminder_title_sms',
  notifications_contribution_dueReminder_body_inApp: 'notifications_contribution_dueReminder_body_inApp',
  notifications_contribution_dueReminder_body_sms: 'notifications_contribution_dueReminder_body_sms',
  notifications_contribution_dueReminder_cta: 'notifications_contribution_dueReminder_cta',
  notifications_contribution_receipt_title_inApp: 'notifications_contribution_receipt_title_inApp',
  notifications_contribution_receipt_title_sms: 'notifications_contribution_receipt_title_sms',
  notifications_contribution_receipt_body_inApp: 'notifications_contribution_receipt_body_inApp',
  notifications_contribution_receipt_body_sms: 'notifications_contribution_receipt_body_sms',
  notifications_contribution_receipt_cta: 'notifications_contribution_receipt_cta',
  // notifications.loan.*
  notifications_loan_overdueReminder_title_inApp: 'notifications_loan_overdueReminder_title_inApp',
  notifications_loan_overdueReminder_title_sms: 'notifications_loan_overdueReminder_title_sms',
  notifications_loan_overdueReminder_body_inApp: 'notifications_loan_overdueReminder_body_inApp',
  notifications_loan_overdueReminder_body_sms: 'notifications_loan_overdueReminder_body_sms',
  notifications_loan_overdueReminder_cta: 'notifications_loan_overdueReminder_cta',
  // notifications.approval.*
  notifications_approval_required_title_inApp: 'notifications_approval_required_title_inApp',
  notifications_approval_required_title_sms: 'notifications_approval_required_title_sms',
  notifications_approval_required_body_inApp: 'notifications_approval_required_body_inApp',
  notifications_approval_required_body_sms: 'notifications_approval_required_body_sms',
  notifications_approval_required_cta: 'notifications_approval_required_cta',
  notifications_approval_decision_approved_title_inApp: 'notifications_approval_decision_approved_title_inApp',
  notifications_approval_decision_approved_title_sms: 'notifications_approval_decision_approved_title_sms',
  notifications_approval_decision_rejected_title_inApp: 'notifications_approval_decision_rejected_title_inApp',
  notifications_approval_decision_rejected_title_sms: 'notifications_approval_decision_rejected_title_sms',
  notifications_approval_decision_body_approved_inApp: 'notifications_approval_decision_body_approved_inApp',
  notifications_approval_decision_body_rejected_inApp: 'notifications_approval_decision_body_rejected_inApp',
  notifications_approval_decision_body_sms: 'notifications_approval_decision_body_sms',
  notifications_approval_decision_cta: 'notifications_approval_decision_cta',
  // notifications.system.* (admin-facing)
  notifications_system_smsDeliveryFailed_title: 'notifications_system_smsDeliveryFailed_title',
  notifications_system_smsDeliveryFailed_body: 'notifications_system_smsDeliveryFailed_body',
  notifications_system_smsDeliveryFailed_cta: 'notifications_system_smsDeliveryFailed_cta',
  notifications_system_smsDeliveryFailed_statusFailed: 'notifications_system_smsDeliveryFailed_statusFailed',
  notifications_system_smsDeliveryFailed_statusRetrying: 'notifications_system_smsDeliveryFailed_statusRetrying',
  notifications_system_smsDeliveryFailed_statusUndeliverable: 'notifications_system_smsDeliveryFailed_statusUndeliverable',
  // SMS template pack – short and standard variants (MVP use cases)
  notifications_sms_meeting_reminder_short: 'notifications_sms_meeting_reminder_short',
  notifications_sms_meeting_reminder_standard: 'notifications_sms_meeting_reminder_standard',
  notifications_sms_contribution_due_short: 'notifications_sms_contribution_due_short',
  notifications_sms_contribution_due_standard: 'notifications_sms_contribution_due_standard',
  notifications_sms_overdue_repayment_short: 'notifications_sms_overdue_repayment_short',
  notifications_sms_overdue_repayment_standard: 'notifications_sms_overdue_repayment_standard',
  notifications_sms_approval_required_short: 'notifications_sms_approval_required_short',
  notifications_sms_approval_required_standard: 'notifications_sms_approval_required_standard',
  notifications_sms_receipt_confirmation_short: 'notifications_sms_receipt_confirmation_short',
  notifications_sms_receipt_confirmation_standard: 'notifications_sms_receipt_confirmation_standard',
  /** Optional: when tenant enables amount in receipt SMS (use with care). */
  notifications_sms_receipt_confirmation_withAmount_standard: 'notifications_sms_receipt_confirmation_withAmount_standard',
  // SMS link text conventions
  notifications_sms_linkOpenApp: 'notifications_sms_linkOpenApp',
  notifications_sms_linkViewDetails: 'notifications_sms_linkViewDetails',
  // Consent/preference reminder (non-critical messages)
  notifications_sms_consentReminder: 'notifications_sms_consentReminder',
  // Preferences screen empty/error
  notifications_preferences_emptyTitle: 'notifications_preferences_emptyTitle',
  notifications_preferences_emptyDescription: 'notifications_preferences_emptyDescription',
  notifications_preferences_errorLoad: 'notifications_preferences_errorLoad',
  admin_support_gate_title: 'admin_support_gate_title',
  admin_support_gate_reasonCode: 'admin_support_gate_reasonCode',
  admin_support_gate_startAccess: 'admin_support_gate_startAccess',
  admin_support_home_title: 'admin_support_home_title',
  admin_support_home_subtitle: 'admin_support_home_subtitle',
  admin_support_home_description: 'admin_support_home_description',
  admin_support_home_inactiveNotice: 'admin_support_home_inactiveNotice',
  admin_trace_financialCorrectionWarning: 'admin_trace_financialCorrectionWarning',
  admin_evidence_auditedView: 'admin_evidence_auditedView',

  // Immutable record / history messaging (reversals, audit)
  immutable_originalRecordPreserved: 'immutable_originalRecordPreserved',
  immutable_reversalCreated: 'immutable_reversalCreated',
  immutable_historyVisible: 'immutable_historyVisible',
  immutable_reversalExplanation: 'immutable_reversalExplanation',
  /** Shown on reversed record detail (e.g. contribution) */
  immutable_recordReversedMessage: 'immutable_recordReversedMessage',

  // Placeholders (VC Pay, VC Learn – later; roadmap/coming-soon surfaces only)
  pay_comingLater: 'pay_comingLater',
  pay_comingSoon: 'pay_comingSoon',
  pay_cardTitle: 'pay_cardTitle',
  pay_cardDescription: 'pay_cardDescription',
  pay_roadmapDescription: 'pay_roadmapDescription',
  learn_comingLater: 'learn_comingLater',
  learn_comingSoon: 'learn_comingSoon',
  learn_cardTitle: 'learn_cardTitle',
  learn_cardDescription: 'learn_cardDescription',
  learn_roadmapDescription: 'learn_roadmapDescription',
} as const;

export type CopyKey = (typeof COPY_KEYS)[keyof typeof COPY_KEYS];
